In [30]:
import pandas as pd
df_compras = pd.read_csv('202201_Compras.csv', sep=';', encoding='cp1252')

In [27]:
df_item_compra = pd.read_csv('202201_ItemCompra.csv', sep=';', encoding='cp1252')

In [34]:
df_item_compra.sample(10)

,Código Órgão,Nome Órgão,Código UG,Nome UG,Número Contrato,Código Item Compra,Descrição Item Compra,Descrição Complementar Item Compra,Quantidade Item,Valor Item
5037,26262,Universidade Federal de São Paulo,153031,UNIFESP-UNIVERSIDADE FEDERAL DE SAO PAULO,92022,1530310600142202100001,LOCACAO APARELHO AR CONDICIONADO,LOCAÇÃO MENSAL DE 11 (ONZE) EQUIPAMENTOS DE AR...,132,"102,00"
10548,52131,Comando da Marinha,788810,ESTACAO NAVAL DO RIO NEGRO,1112021,7888100500011202100205,MANUTENCAO INDUSTRIAL,SENSOR DE TEMPERATURA DA ÁGUA,1,"1500,00"
4923,25000,Ministério da Economia - Unidades com vínculo,170138,DELEGACIA DA RFB EM RIBEIRAO PRETO,82021,1701380500001202100009,PRESTACAO DE SERVICOS DE APOIO ADMINISTRATIVO,PRESTAÇÃO DE SERVIÇOS DE APOIO ADMINISTRATIVO ...,1,"5180,93"
10365,52131,Comando da Marinha,788810,ESTACAO NAVAL DO RIO NEGRO,1112021,7888100500011202100476,MANUTENCAO INDUSTRIAL,CORREIA DO ALTERNADOR,5,"100,00"
10245,52131,Comando da Marinha,788810,ESTACAO NAVAL DO RIO NEGRO,1112021,7888100500011202100076,MANUTENCAO INDUSTRIAL,KIT COMPLETO DE TUBOS DE RETORNO DE COMBUSTÍVEL,4,"1727,00"
10690,52121,Comando do Exército,160069,CENTRO DE OBTENCOES DO EXERCITO,1112021,1600690500020202100021,RAÇÃO HUMANA DE EMERGÊNCIA,"RAÇÃO HUMANA DE EMERGÊNCIA, TIPO RAÇÃO OPERACI...",3,"49,84"
12792,22201,Instituto Nacional de Colonização e Reforma A,373029,SUPERINTENDENCIA REGIONAL DE RORAIMA - SR(RR),13372021,0,Inválido,Inválido,10,"100,00"
2362,26443,Empresa Brasileira de Serviços Hospitalares,155010,HOSPITAL UNIVERSITARIO DA UFMA,32022,1550100500090202100001,GASOLINA,"GASOLINA, USO PARA AUTOMOTIVOS, CLASSIFICAÇÃO ...",14000,"4,96"
12716,26439,Instituto Federal de São Paulo,158329,IFSP - CAMPUS SAO ROQUE,13292022,0,Inválido,Inválido,0,"3533,00"
3355,26350,Fundação Universidade Federal da Grande Doura,154502,FUNDACAO UNIVERSIDADE FED. DA GRANDE DOURADOS,42022,1545020500020202100001,FRUTA,"FRUTA, TIPO ABACATE FORTUNA, APRESENTAÇÃO NATURAL",202,"6570,00"

In [29]:
tamanho_maximo = df_item_compra['Descrição Complementar Item Compra'].apply(len).max()
tamanho_maximo

1247

In [54]:
tamanho_maximo = df_compras['Objeto'].apply(len).max()
tamanho_maximo

520

In [38]:
df_item_compra.sample(10)

,Código Órgão,Nome Órgão,Código UG,Nome UG,Número Contrato,Código Item Compra,Descrição Item Compra,Descrição Complementar Item Compra,Quantidade Item,Valor Item
1933,26431,Instituto Federal do Piauí,158359,INST. FED. PIAUI/CAMPUS PAULISTANA,22022,0,Inválido,Inválido,15,"130,00"
788,26443,Empresa Brasileira de Serviços Hospitalares,155013,HOSPITAL UNIVERSITARIO ONOFRE LOPES,12022,1550130700006202100001,MANUTENCAO APARELHOS MEDICOS - HOSPITALARES,SERVIÇO DE MANUTENÇÃO PREVENTIVA E CORRETIVA C...,12,"37000,00"
5171,26404,Instituto Federal Baiano,151889,IF BAIANO CAMPUS BOM JESUS DA LAPA,112021,1518890600010202100001,LEGUME IN NATURA,"LEGUME IN NATURA, TIPO ABÓBORA CABOTIÁ/ JAPONESA",800,"3,00"
11902,26435,Instituto Federal do Rio Grande do Norte,152756,INST. FED. DO RN / CAMPUS PARNAMIRIM,1872021,0,Inválido,Inválido,5,"98,00"
7077,36000,Ministério da Saúde - Unidades com vínculo di,250059,INSTITUTO NACIONAL DE CARDIOLOGIA,272021,2500590500006202000012,HIDRÓXIDO DE SÓDIO,"HIDRÓXIDO DE SÓDIO, ASPECTO FÍSICO EM LENTILHA...",0,"0,07"
12461,36201,Fundação Oswaldo Cruz,254445,INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS,5802021,2544450700267202100054,ATUADOR ELÉTRICO / MECÂNICO,"ATUADOR;1.1/4'-1.1/2';NF;968740Z11+1300,GEMU;A...",7,"2340,15"
3770,26270,Fundação Universidade do Amazonas,154039,FUNDACAO UNIVERSIDADE DO AMAZONAS,52022,1540390500022202100220,AR CONDICIONADO - MANUTENCAO DE SISTEMAS / LIM...,MANUTENÇÃO CORRETIVA EM AR- CONDICIONADO DE PR...,2,"15000,00"
5391,30108,Departamento de Polícia Federal,200376,SUPERINTENDENCIA REGIONAL NO ESTADO DE GO,132021,0,Informação protegida por sigilo nos termos da ...,Informação protegida por sigilo nos termos da ...,188500,"0,02"
941,25000,Ministério da Economia - Unidades com vínculo,170135,DELEGACIA DA RFB EM BAURU,12022,0,Inválido,Inválido,3,"3367,42"
48,26408,Instituto Federal do Maranhão,158290,INST.FED.DO MARANHAO/CAMPUS SANTA INES,12021,1582900500001202100001,APARELHO AR CONDICIONADO,APARELHO CONDICIONADOR DE AR (UNIDADE EVAPORAD...,2400,"10,00"

In [39]:
df_compras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3237 entries, 0 to 3236
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Número do Contrato                  3237 non-null   int64
 1   Objeto                              3237 non-null   object
 2   Fundamento Legal                    17 non-null     object
 3   Modalidade Compra                   3237 non-null   object
 4   Situação Contrato                   3237 non-null   object
 5   Código Órgão Superior               3237 non-null   int64
 6   Nome Órgão Superior                 3237 non-null   object
 7   Código Órgão                        3237 non-null   int64
 8   Nome Órgão                          3237 non-null   object
 9   Código UG                           3237 non-null   int64
 10  Nome UG                             3237 non-null   object
 11  Data Assinatura Contrato            3237 non-null   object
 12  Data Publicação DOU                 3237 non-null   object
 13  Data Início Vigência                3237 non-null   object
 14  Data Fim Vigência                   3236 non-null   object
 15  Código Contratado                   3237 non-null   object
 16  Nome Contratado                     3237 non-null   object
 17  Valor Inicial Compra                3237 non-null   object
 18  Valor Final Compra                  3237 non-null   object
 19  Número Licitação                    3237 non-null   int64
 20  Código UG Licitação                 2745 non-null   float64
 21  Nome UG Licitação                   2745 non-null   object
 22  Código Modalidade Compra Licitação  2745 non-null   float64
 23  Modalidade Compra Licitação         2745 non-null   object
dtypes: float64(2), int64(5), object(17)
memory usage: 607.1+ KB

In [49]:
filtrado = df_compras[['Número do Contrato', 'Objeto', 'Fundamento Legal']]

In [51]:
filtrado.sort_values(by=['Número do Contrato']).head(15)

,Número do Contrato,Objeto,Fundamento Legal
1646,11999,Objeto: AKLSJFKLASJFKLSJKLASJFKJASDKLJFSKLJFKL...,NaN
1305,12001,Objeto: CONTRATAÇÃO DE PRESTAÇÃO DE SERVIÇOS P...,NaN
281,12008,Objeto: FORNECIMENTO DE AGUA E COLETA DE ESGOT...,NaN
3022,12017,Objeto: SERVIÇO DE FORNECIMENTO DE ENERGIA ELÉ...,NaN
460,12018,"Objeto: SOLUÇÃO CONTINUADA DE IMPRESSÃO, CÓPIA...",NaN
1013,12018,"Objeto: CESSÃO DE USO, A TÍTULO ONEROSO, DE PA...",NaN
3184,12018,Objeto: CONCESSÃO ONEROSA DE USO DO ESPAÇO FÍS...,NaN
556,12018,Objeto: O OBJETO DA PRESENTE CESSÃO DE USO ASS...,NaN
289,12019,"Objeto: CESSÃO DE USO, A TÍTULO ONEROSO, DA ÁR...",NaN
450,12019,Objeto: CESSÃO DE USO DE BEM IMÓVEL PRÓPRIO NA...,NaN
1414,12020,Objeto: CONCESSÃO ADMINISTRATIVA DE USO DE BEM...,NaN
1528,12020,Objeto: CONTRATAÇÃO DE SERVIÇOS DE FACILIDADES...,NaN
66,12020,Objeto: CONTRATAÇÃO DE SERVIÇOS DE TELECOMUNIC...,NaN
379,12020,Objeto: CESSÃO ONEROSA DE USO DE BEM IMÓVEL DA...,NaN
1902,12020,Objeto: PRESTAÇÃO COMPLEMENTAR DE SERVIÇOS DE ...,NaN

In [52]:
filtrado['Fundamento Legal'].unique()

array([nan, 'Lei 10.520/02, Artigo 1 , Inciso 00',
       'Fundamento Legal: Lei nº13.303,de 30/06/2016,DEC.nº8.945,de 27/12/2016,Lei 10.520,de 17/07/02,DEC.nº10.024,de 20/09/19,LC nº 123,de 14/12/06.',
       'Fundamento Legal: Art 421, RLC da Conab',
       'Fundamento Legal: Lei 8666/93',
       'Fundamento Legal: Art 421 RLC Conab',
       'Fundamento Legal: Lei n  13.303, de 30 de junhode 2016, do Decreto 8.945, de 27 de dezembro de2016, do Decretc. 10.024,de 20/09/2019...',
       'Fundamento Legal: rilc cbtu e lei 13.303/2016',
       'Lei 8.666/93, Artigo 24 , Inciso 04',
       'Fundamento Legal: RILC CBTU e LEI 13.303/2016',
       'Lei 8.666/93, Artigo 24 , Inciso 02',
       'Fundamento Legal: LEI 13303/16',
       'Lei 8.666/93, Artigo 25 , Inciso 00',
       'Fundamento Legal: LEI 8666/93'], dtype=object)